---
site:
  title: "Convert2RHEL with Red Hat Insights"
  url: https://github.com/rhpds/showroom_template_zero
  start_page: modules::01-pre-conversion-analysis-for-converting-to-rhel.adoc

content:
  sources:
    - url: ./
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.2/bundle.zip
    snapshot: true

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora